DEFINE TEMP-TABLE tta FIELD i AS INTEGER.
DEFINE TEMP-TABLE ttb UNDO FIELD i AS INTEGER.
DEFINE TEMP-TABLE ttc NO-UNDO FIELD i AS INTEGER.

DEFINE TEMP-TABLE ttd LIKE tta.
DEFINE TEMP-TABLE tte LIKE ttb.
DEFINE TEMP-TABLE ttf LIKE ttc.

DEFINE TEMP-TABLE ttg NO-UNDO LIKE tta.
DEFINE TEMP-TABLE tth UNDO LIKE ttc.
