FORM "Title" WITH FRAME frm1.
DEFINE VARIABLE menu AS CHARACTER NO-UNDO EXTENT 4 FORMAT "x(7)" INITIAL [ "AAA", "BBB", "CCC", "DDD" ].
REPEAT:
  VIEW FRAME frm1.
  DISPLAY menu WITH FRAME f-menu CENTERED.
  HIDE MESSAGE.
  CHOOSE FIELD menu GO-ON (F5) AUTO-RETURN WITH FRAME f-menu.
END. 
