DEFINE TEMP-TABLE tt1 FIELD fld1 AS INT FIELD fld2 AS INT FIELD fld3 AS CHAR EXTENT 10.
DEFINE QUERY q1 FOR tt1.
DEFINE BROWSE b1 QUERY q1 DISPLAY tt1.fld1 ENABLE tt1.fld1 WITH 10 DOWN.

DEFINE FRAME f1 b1
  WITH SIDE-LABELS AT ROW 2 COLUMN 2.
  
DEFINE STREAM sin.
DEFINE BUFFER buf1 FOR tt1.


APPLY "VALUE-CHANGED" TO BROWSE b1.
APPLY "VALUE-CHANGED" TO QUERY q1.
APPLY "VALUE-CHANGED" TO TEMP-TABLE tt1.
APPLY "VALUE-CHANGED" TO FRAME f1.
APPLY "VALUE-CHANGED" TO STREAM sin.
APPLY "VALUE-CHANGED" TO BUFFER buf1.