DEFINE TEMP-TABLE tt1 FIELD fld1 AS INT FIELD fld2 AS INT FIELD fld3 AS CHAR EXTENT 10.
DEFINE QUERY q1 FOR tt1.
DEFINE BROWSE b1 QUERY q1 DISPLAY tt1.fld1 ENABLE tt1.fld1 WITH 10 DOWN.
DEFINE QUERY q2 FOR tt1.
DEFINE BROWSE b2 QUERY q2 DISPLAY tt1 EXCEPT tt1.fld3[2 FOR 4] WITH 10 DOWN.
