class rssw.pct.ScopeTest:

  method public void methd1():
    return.
    catch err AS Progress.Lang.Error:
    end catch.
  end method.

  define public property zz as character no-undo
    get.
    set (arg as char):
      define variable i as int no-undo.
      do i = 1 to num-entries(arg):
      
      end.
    end set.

  define public property zz2 as character no-undo
    get.
    set (arg as char):
      define variable i as int no-undo.
      do i = 1 to num-entries(arg):
      
      end.
    end set.

end class.
