/********************************************************************************
 * Copyright (c) 2015-2021 Riverside Software
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU Lesser General Public License v3.0
 * which is available at https://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * SPDX-License-Identifier: EPL-2.0 OR LGPL-3.0
 ********************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.04 at 08:32:00 AM UTC 
//

package com.progress.xref;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uri.schemas_progress_com.xrefd._0005 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uri.schemas_progress_com.xrefd._0005
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrossReference }
     * 
     */
    public CrossReference createCrossReference() {
        return new CrossReference();
    }

    /**
     * Create an instance of {@link CrossReference.Source }
     * 
     */
    public CrossReference.Source createCrossReferenceSource() {
        return new CrossReference.Source();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference }
     * 
     */
    public CrossReference.Source.Reference createCrossReferenceSourceReference() {
        return new CrossReference.Source.Reference();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference.DatasetRef }
     * 
     */
    public CrossReference.Source.Reference.DatasetRef createCrossReferenceSourceReferenceDatasetRef() {
        return new CrossReference.Source.Reference.DatasetRef();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference.ClassRef }
     * 
     */
    public CrossReference.Source.Reference.ClassRef createCrossReferenceSourceReferenceClassRef() {
        return new CrossReference.Source.Reference.ClassRef();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference.StringRef }
     * 
     */
    public CrossReference.Source.Reference.StringRef createCrossReferenceSourceReferenceStringRef() {
        return new CrossReference.Source.Reference.StringRef();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference.ParameterRef }
     * 
     */
    public CrossReference.Source.Reference.ParameterRef createCrossReferenceSourceReferenceParameterRef() {
        return new CrossReference.Source.Reference.ParameterRef();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference.InterfaceRef }
     * 
     */
    public CrossReference.Source.Reference.InterfaceRef createCrossReferenceSourceReferenceInterfaceRef() {
        return new CrossReference.Source.Reference.InterfaceRef();
    }

    /**
     * Create an instance of {@link CrossReference.Source.Reference.DatasetRef.Relation }
     * 
     */
    public CrossReference.Source.Reference.DatasetRef.Relation createCrossReferenceSourceReferenceDatasetRefRelation() {
        return new CrossReference.Source.Reference.DatasetRef.Relation();
    }

}
