PROGRAM_ROOT F0/0:0 -- Block -- Scope
  CLASS F0/1:1
    DEFINE F0/2:3
    DEFINE F0/3:3
    DEFINE F0/4:3
    CONSTRUCTOR F0/10:3 -- Block -- Scope
      MESSAGE F0/11:5
      MESSAGE F0/12:5
    METHOD F0/15:3 -- Block -- Scope
      DO F0/16:5 -- Block
        MESSAGE F0/17:7
        DO F0/18:7 -- Block
          REPEAT F0/19:9 -- Block
            MESSAGE F0/20:11
      FINALLY F0/24:5
        MESSAGE F0/25:7
        MESSAGE F0/26:7

