PROGRAM_ROOT F0/0:0 -- Block -- Scope
  CLASS F0/1:0
    DEFINE F0/2:2
    DEFINE F0/3:2
    DEFINE F0/4:2
    CONSTRUCTOR F0/10:2 -- Block -- Scope
      MESSAGE F0/11:4
      MESSAGE F0/12:4
    METHOD F0/15:2 -- Block -- Scope
      DO F0/16:4 -- Block
        MESSAGE F0/17:6
        DO F0/18:6 -- Block
          REPEAT F0/19:8 -- Block
            MESSAGE F0/20:10
      FINALLY F0/24:4
        MESSAGE F0/25:6
        MESSAGE F0/26:6

