
/*------------------------------------------------------------------------
    File        : BaseInterface
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike
    Created     : Tue Dec 16 21:40:00 CET 2014
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE Consultingwerk.ProparseTests.InterfaceInheritance.BaseInterface:  
  
END INTERFACE.