
/*------------------------------------------------------------------------
    File        : ExtendedInterface
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike
    Created     : Tue Dec 16 21:40:17 CET 2014
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING Consultingwerk.ProparseTests.InterfaceInheritance.BaseInterface.

INTERFACE Consultingwerk.ProparseTests.InterfaceInheritance.ExtendedInterface INHERITS com.BaseInterface:  
  
END INTERFACE.