 
 /*------------------------------------------------------------------------
    File        : SerializableClass
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike
    Created     : Tue Dec 16 21:35:01 CET 2014
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Consultingwerk.ProparseTests.Serializable.SerializableClass SERIALIZABLE USE-WIDGET-POOL: 

END CLASS.