class TooManyParams:

  define public event event01 signature void ( input sender as Progress.Lang.Object, input e as Progress.Lang.Object ).
  define public event event02 signature void ( input sender as Progress.Lang.Object, input e as Progress.Lang.Object ).
  define public event event03 signature void ( input sender as Progress.Lang.Object, input e as Progress.Lang.Object, input xyz as int ).

  define public property prop01 as integer get. set.

end class.
